### ISSUE TITLE
Can not get Lucida to install. 

### ISSUE THREAD

**Issue by Kezryk** [claritylab/lucida#126]
Every reference i find to install Lucida doesnt work. Missing folders wrong paths etc. Needs a better way to install and use..

**Comment by yunshengb** [comment]
First of all, I completely understand your feelings, because I experienced the same frustration when I saw errors like those.

I'd like to suggest using Kubernetes to deploy Lucida, because Docker containers tend to be stable and portable once they are built. In other words, they are immune to new updates in this repo.

However, if you want to compile Lucida locally, please understand that frequent updates, especially those installation scripts for dependencies (e.g. fbthrift, kaldi), may not work. Besides, the dependencies themselves may get broken. For example, fbthrift recently had an [issue](https://github.com/facebook/wangle/issues/59) due to invalid link embedded in their installation script for another dependency. All these problems can be "solved" by letting users install dependencies themselves. For example, we could have given a general instruction on how to clone the opencv repo and install it. However, we choose to provide detailed scripts for installing all needed dependencies, which leads to the problems described above.

I am very willing to help you on compilation issues, and I apologize for any inconvenience. Please provide specific issues that you are encountering and I will try to respond as soon as I can. 

Thank you very much.

**Comment by saijel** [comment]
Hi @Kezryk, we are currently working on making the build system easier and reduce dependencies. Please open a new issue and provide error logs so we can help you compile for the time being. Thanks!
