### ISSUE TITLE
macOS: Lucida Docker Deployment

### ISSUE THREAD

**Issue by azizur** [claritylab/lucida#134]
Hi there,

I am trying to learn how Lucida works and wanted to try out the speech recognition and how I can train it with my own audio samples mp3s.

I am trying to run Lucida in using Docker Version 1.12.3 on MacOS locally.

When I follow the instructions on [Lucida Docker Deployment](https://github.com/claritylab/lucida#lucida-docker-deployment)

I am getting the following errors:
```
docker: Error response from daemon: Mounts denied:
The path /var/lib/kubelet/
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
..
./cluster_up.sh: line 22: /usr/bin/kubectl: Operation not permitted
chmod: /usr/bin/kubectl: No such file or directory
./cluster_up.sh: line 24: kubectl: command not found
./cluster_up.sh: line 25: kubectl: command not found
./cluster_up.sh: line 26: kubectl: command not found
Exiting... Wait until 'kubectl get pod' does not give error. Fix permission errors if exist. Then run 'start_services.sh'.
Meanwhile, you can 'watch docker ps' to see how Kubernetes sets up the cluster via Docker containers.
```

**Comment by yunshengb** [comment]
Hi,

It seems like a permission error, and [this](https://github.com/vyshane/kid/issues/14) may help. 

If you want to train the speech recognition system, I recommend using Ubuntu 14.04 for development, and using OS X only to deploy the Docker containers, because all the scripts in this repo have been tested on Ubuntu 14.04. 

Let me know if that error still exists, and I am willing to further help. Thanks!

**Comment by saijel** [comment]
Hi @azizur, please open a new issue if you are still seeing this problem. Thanks!
