### ISSUE TITLE
Cannot close Lucida session

### ISSUE THREAD

**Issue by tabz11** [claritylab/lucida#233]
Hi,

I have tried installing Lucida but some error occurred so, had to install and make again, Now problem I'm getting is it is saying Lucida session already exists, have already checked with `lsof -i` and nothing is working on port 3000. Please advise how can I close Lucida session and start a fresh one?

**Comment by JeremyARussell** [comment]
If I'm understanding you're situation correctly from context you're running things locally with `make start_all` or `make start_all_secure` and then getting that session already exists error right?

If that's the case you should be able to just run `tmux attach` which will let you attach to whatever tmux session is already created(which at that point should be the lucida session).

If all that works then everything is actually running as expected. What's going on is the scripts which run that set up the lucida command center and services use a program called tmux to manage the various services that need to be ran. And for some reason the script doesn't automatically attach to the existing tmux session if it detects the session exists.

**Comment by tabz11** [comment]
yes, now I want to close Lucida and remove it. how can I do it?

**Comment by JeremyARussell** [comment]
Check out this tmux cheat sheet - https://gist.github.com/MohamedAlaa/2961058. It has a list of all the common commands you'll want to know in order to use lucida, which uses tmux. I'm not sure if anyone has any forks where a different screen multiplexer, or something like supervisord (which are really two different kinds of programs which can be used to handle creating all the processes/services that lucida uses to run) up but I've been sticking with tmux myself.

In any case, the command you're wanting to use is ```tmux kill-session -t myname``` where you replace myname with lucida. So it should ultimately look like this if you haven't made any changes to the scripts that start lucida. ```tmux kill-session -t lucida```

**Comment by tabz11** [comment]
Many Thanks it really helped

**Comment by JeremyARussell** [comment]
Awesome, I'm glad I could help.
