### ISSUE TITLE
boost lib dependency should be added in the get_dependencies.sh?

### ISSUE THREAD

**Issue by HarveyLiuFly** [claritylab/lucida#34]
since it's required by building the match in IMM module

**Comment by LeonardKoenig** [comment]
It's already in (libboost-all-dev) - at least for Ubuntu

**Comment by sedrubal** [comment]
Mh it wasn't installed after I ran the script, too. I had to install following manually:

 - swig / swig2.0 (I installed both ;) )
 - python-dev
 - libboost-all-dev / libboost-dev libboost-program-options1.55-dev libboost-filesystem1.55-dev

**Comment by electrickite** [comment]
get-dependencies.sh is not installing all of the dependencies it should when run on Ubuntu 14.04 because of issue #24

The first apt-get install fails because ffmpeg is not included in the 14.04 package repository, so none of the dependencies on that line are installed.

A solution might be to add an ffmpeg PPA prior to that in the script or to compile from source.

**Comment by LeonardKoenig** [comment]
The best would be to remove the script from the GitHub, imho (sources shouldn't be Distro-specific), or atleast provide it in a seperate folder:
- Installscripts:
  - Ubuntu
  - Fedora ...

I'm just trying hard to get it working under Arch but several builds fail with syntax error etc.

**Comment by sedrubal** [comment]
Yes, I think that would be the best.

But I think, it's no good idea to install things completely automated and even add PPAs automated, because the user should decide what he wants to install. It should be more clear, what the script does...

**Comment by jhauswald** [comment]
superseded by #104
