### ISSUE TITLE
ASR accuracy with command-center/test.wav

### ISSUE THREAD

**Issue by dsmcfarl** [claritylab/lucida#90]
I successfully built and ran the asr, qa, and command-center; then ran "./ccclient --asr test.wav 8081" and received the correct answer, but the asr engine interpreted the test.wav as "who invented enough letters" instead of "who invented peanut butter".

Is this behavior expected with the test.wav file and the default asr config?

**Comment by jhauswald** [comment]
This was recorded audio I had that I didn't get a chance to properly test since Ive been traveling and had limited internet connectivity (it was a challenge just getting Lucida pushed!)

It served its purpose though since you were able to test it! I'm going to grab the ones from Sirius and add them as soon as I can. What's currently there is a sample database of a few facts by the way.

**Comment by dsmcfarl** [comment]
That makes sense. I had not dug into it deep enough to realize the database only contained a few facts.  Thanks for the quick reply and sharing this great project.

**Comment by jhauswald** [comment]
Hey I updated the inputs (e97d20c). Some are meant for the small database (peanut butter and height of building) while the others are for the wikipedia database. I'll close this for now but let me know if you need anything else!
